import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  Bell,
  Calendar,
  Camera,
  CircleX,
  DollarSign,
  Eye,
  EyeOff,
  Filter,
  Home,
  Loader2,
  Mail,
  Menu,
  Plus,
  Settings,
  User,
  Users,
  X,
} from "lucide-react";

export const icons = {
  alertCircle: AlertCircle,
  alertTriangle: AlertTriangle,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  bell: Bell,
  camera: Camera,
  calendar: Calendar,
  circleX: CircleX,
  close: X,
  dollarSign: DollarSign,
  eye: Eye,
  eyeOff: EyeOff,
  filter: Filter,
  home: Home,
  mail: Mail,
  menu: Menu,
  plus: Plus,
  settings: Settings,
  spinner: Loader2,
  user: User,
  users: Users,
};
