name: Dev Web App Deploy Workflow

on:
  push:
    branches:
      - staging
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix: 
        node-version: [22.x]
      
    steps:  
    - uses: actions/checkout@v2
    - name: Use Node.js ${{matrix.node-version}}
      uses: actions/setup-node@v2
      with: 
        node-version: ${{matrix.node-version}}

    - name: Install Dependencies
      run: npm ci

    - name: Install Railway CLI
      run: curl -fsSL https://railway.app/install.sh | sh

    - name: Set server variables on Railway
      run: |
        variables=(
          "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}"
          "MONGODB_URI=${{ secrets.MONGODB_URI }}"
          "EMAIL_TO=${{ secrets.EMAIL_TO }}"
        )
        
        SET_FLAGS=""
        for var in "${variables[@]}"; do
          SET_FLAGS+="--set \"$var\" "
        done

        # Evaluate the final Railway CLI call
        eval "railway variables --service website $SET_FLAGS"

      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_STAGING_TOKEN }}

    - name: Deploy to Railway
      run: railway up --service website
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_STAGING_TOKEN }}